package org.tonguetied.usermanagement;

/**
 * Class containing utility methods for tests in the user managament packages.
 * 
 * @author bsion
 *
 */
public class UserTestUtils
{
    /**
     * Lifted from the spring security source.
     * 
     * @param mergedPasswordSalt as generated by 
     * <code>mergePasswordAndSalt</code>
     * @return an array, in which the first element is the password and the 
     * second the salt
     * @throws IllegalArgumentException if mergedPasswordSalt is null or empty
     */
    protected static final String[] demergePasswordAndSalt(String mergedPasswordSalt) 
    {
        if ((mergedPasswordSalt == null) || "".equals(mergedPasswordSalt)) {
            throw new IllegalArgumentException("Cannot pass a null or empty String");
        }

        String password = mergedPasswordSalt;
        String salt = "";

        int saltBegins = mergedPasswordSalt.lastIndexOf("{");

        if ((saltBegins != -1) && ((saltBegins + 1) < mergedPasswordSalt.length())) {
            salt = mergedPasswordSalt.substring(saltBegins + 1, mergedPasswordSalt.length() - 1);
            password = mergedPasswordSalt.substring(0, saltBegins);
        }

        return new String[] {password, salt};
    }
}
